### ISSUE TITLE
OpenMC as a git submodule

### ISSUE THREAD

**Issue by paulromano** [aprilnovak/Okapi#1]
Since Okapi relies on OpenMC's C API, which is likely to be unstable for a while, it might be good to have OpenMC as a git submodule so that a user knows what version of OpenMC will work when compiling Okapi.  Then, if the C API changes, we can update the calls to OpenMC C functions and the git submodule simultaneously.

**Comment by aprilnovak** [comment]
This is a good idea, this would reduce a lot of headaches!

**Comment by aprilnovak** [comment]
Closed in #12.
